version: "3"

services:
  app:
    image: darren/opencv-cuda:cuda-11.3.1-cudnn8-opencv-4.5.3
    build: 
      context: .
      args:
        - XAUTH_TOKEN
        - GPU_COMPUTE_CAPABILITY
    command: tail -F anything
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./albion-online/:/albion-online
    devices:
      - ${WEBCAM_HOST}:${WEBCAM_CONTAINER}
    network_mode: host
