version: "3"

services:
  yolo:
    image: darren/opencv-cuda:cuda-11.3.1-cudnn8-opencv-4.5.3
    build: 
      context: yolo/.
      args:
        - XAUTH_TOKEN=${XAUTH_TOKEN}
        - GPU_COMPUTE_CAPABILITY=${GPU_COMPUTE_CAPABILITY}
        - OPENCV_VERSION=${OPENCV_VERSION}
    command: tail -F anything
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./albion-online/:/albion-online
    devices:
      - ${WEBCAM_HOST}:${WEBCAM_CONTAINER}
    network_mode: host
